_target_: src.models.cvae_module.CVAELitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_cvae.SimpleCVAE
  input_size: 16384
  condition_size: 16384
  latent_size: 5
  encoder_lin1_size: 512
  encoder_lin2_size: 512
  encoder_lin3_size: 512
  decoder_lin1_size: 512
