defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: False
  auto_insert_metric_name: False
  every_n_epochs: 1
  save_top_k: -1  # -1 means no checkpoints are deleted

early_stopping:
  monitor: "val/loss"
  patience: 100
  mode: "min" 
  # min_delta: 0.01 # minimum change in the monitored quantity to qualify as an improvement

model_summary:
  max_depth: -1
