# @package _global_

defaults:
  - _self_
  - data: default.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: autoencoder.yaml
  - logger: csv
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
# ckpt_path: logs/train/runs/2023-08-09_02-52-26/checkpoints/epoch_049.ckpt
