source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.1'

# group :jekyll_plugins do
#   gem 'jekyll-feed', '0.11.0'
#   gem 'jekyll-seo-tag', '2.5.0'
# #   gem 'jekyll-sitemap', '1.2.0'
# end

gem "tzinfo", "~> 2.0"

gem "tzinfo-data", "~> 1.2023"

gem "jekyll-sitemap", "~> 1.4"

gem "jekyll-seo-tag", "~> 2.8"

gem "jekyll-feed", "~> 0.17.0"

gem "jekyll-prettier", "~> 0.0.0"

gem "kramdown", "~> 2.4"

gem "rouge", "~> 4.1"
